### ISSUE TITLE
Checkpoint will be released?

### ISSUE THREAD

**Issue by QYFfly** [tuanle618/eqgat-diff#1]
Hi, I can't find pretrained checkpoint in repo. Can you release it?

**Comment by tuanle618** [comment]
Hello @QYFfly, currently we share the pretrained checkpoints on request. I will discuss with my supervisor how this can be handled in the future. 

In the meantime, would you mind sending me an email to tuan.le@pfizer.com ?
I can send you a link for download then.

Tuan

**Comment by QYFfly** [comment]
Got it. I’ll send an email to tuan.le@pfizer.com soon to get the download link.
